Repository canonical/ght, pull requests merged in 2022-02, with the labels that each got.

#20 fix snap security failures
  snap/snapcraft.yaml
Labels: Review: QA +1

#21 Added delete command
  src/automations/Job.ts
  src/automations/SSO.ts
  src/index.ts
Labels: Review: Code +1 (with changes), Review: QA +1

#23 Errors are made human readable
  src/automations/Job.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#25 Added job selection interface
  .eslintrc
  package.json
  src/automations/Job.ts
  src/automations/JobPost.ts
  src/automations/SSO.ts
  src/common/constants.ts
  src/common/pageUtils.ts
  src/index.ts
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#29 Display unique job post names to the user
  src/automations/JobPost.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#32 Added regions to interactive UI
  src/automations/Job.ts
  src/automations/JobPost.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#35 Updated logs
  src/automations/Job.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#39 Updated regions
  src/common/regions.ts
Labels: Review: Code +1, Review: QA +1

#37 Added renovate rule to restrict node-fetch and ora packages versions
  renovate.json
Labels: Review: Code +1 (with changes)

#40 Updated add-post command's name
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#41 Filtered displayed job posts
  src/automations/JobPost.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#42 Added an error that will be thrown if job post to be cloned doesnt exist on Canonical board
  src/automations/Job.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#44 Added option to delete posts before adding them
  src/index.ts
Labels: Review: Code +1 (with changes), Review: QA +1

#46 Added logs to authentication part
  src/automations/SSO.ts
  src/index.ts
Labels: Review: Code +1 (with changes), Review: QA +1

#50 Updated help descriptions of the commands
  src/automations/Job.ts
  src/automations/JobPost.ts
  src/automations/SSO.ts
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#59 rename add-posts to replicate
  src/index.ts
Labels: Review: Code +1, Review: QA +1

#60 Updated job info gathering method
  src/automations/Job.ts
Labels: Review: Code +1, Review: QA +1

#63 Fixed typo in "credentials"
  src/automations/SSO.ts
Labels: Review: Code +1, Review: QA +1

#58 delete us-boston region
  src/common/regions.ts
Labels: Review: Code +1

#61 Rename snap to `ghtctl`
  snap/snapcraft.yaml
Labels: Review: Code needed, Review: QA needed
