Repository canonical/ght, pull requests merged in 2022-11, with the labels that each got.

#169 fix one of the timeouts
  src/assign-graders/LoadBalancer.ts
Labels: Review: Code +1

#171 Set the default viewport to null
  src/automations/SSO.ts
Labels: Review: Code +1, Review: QA +1

#170 Update version in snapcraft.yaml
  snap/snapcraft.yaml
Labels: Review: Code +1

#174 Revert "Merge pull request #166 from canonical/add-macos-installation…
  README.md
  ght
Labels: Review: QA +1
